DATASET:
  root_dataset: "./data/"
  list_train: "./data/map20kTrain.odgt"
  list_val: "./data/map20kVal.odgt"
  num_class: 43
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  classInfo: "./data/map20kClasses.json"

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "ocr"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr/encoder_epoch_50.pth"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr/decoder_epoch_50.pth"
  fc_dim: 720

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 30
#  start_epoch: 30 
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 32
  disp_iter: 50
  seed: 304
  eval: False

VAL:
  visualize: False
  checkpoint: "epoch_77.pth"

TEST:
  checkpoint: "epoch_50.pth"
  result: "./"

DIR: "weights/map20k-hrnetv2-ocr_2/"
