DATASET:
  root_dataset: "./data/"
  list_train: "./data/map20kTrain.odgt"
  list_val: "./data/map20kVal5.odgt"
  list_stats: "./data/map20kTrain.odgt"
  num_class: 44
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  classInfo: "./data/map20kClasses.json"

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "ocr"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/encoder_epoch_30.pth"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/decoder_epoch_30.pth"
  fc_dim: 720
  spatial: False

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 50
  start_epoch: 28 
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.01
  lr_decoder: 0.1
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 50
  seed: 304
  eval: False

VAL:
  visualize: False
  checkpoint: "epoch_30.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "weights/map20k-hrnetv2-ocr_2/"
