DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside15k_train.odgt"
  list_val: "./data/outside15k_val_small.odgt"
  list_stats: "./data/outside15k_all.odgt"
  num_class: 24
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  random_crop: True
  classInfo: "./data/outside15k.json"

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 4
  num_epoch: 40
  start_epoch: 20
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/outside30k-mobilenetv2dilated-c1_deepsup"
