DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside30k_train.odgt"
  list_val: "./data/outside30k_val.odgt"
  list_stats: "./data/outside30k_val.odgt"
  num_class: 27
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True
  random_crop: False
  classInfo: "./data/outside30k.json"

MODEL:
  arch_encoder: "hrnetv2"
  arch_decoder: "upernet"
  fc_dim: 720
  # weights_encoder: "weights/outside30k-hrnetv2-ocr_test/encoder_epoch_50.pth"
  # weights_encoder: "weights/outside30k-resnet50-upernet/decoder_epoch_69.pth"
  spatial: False

TRAIN:
  batch_size_per_gpu: 1
  # start_epoch: 32 
  num_epoch: 30
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 50
  seed: 304
  eval: False

VAL:
  visualize: False
  checkpoint: "epoch_30.pth"

TEST:
  checkpoint: "epoch_50.pth"
  result: "./test_dataset/"

DIR: "weights/outside30k-resnet50-upernet/"
