DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside30k_train.odgt"
  list_val: "./data/outside30k_val50.odgt"
  list_stats: "./data/outside30k_val.odgt"
  num_class: 27
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1100
  padding_constant: 32
  segm_downsampling_rate: 1
  random_flip: True
  random_crop: True
  classInfo: "./data/outside30k.json"

MODEL:
  arch_encoder: "hrnetv2"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/encoder_epoch_30.pth"
  arch_decoder: "ocr"
#  weights_encoder: "./ckpt/ade20k-hrnetv2-ocr_2/decoder_epoch_30.pth"
  fc_dim: 720
  spatial: False

TRAIN:
  batch_size_per_gpu: 1
  # start_epoch: 32 
  num_epoch: 30
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 50
  seed: 304
  eval: False
  ocr_use_gt: True

VAL:
  visualize: False
  checkpoint: "epoch_40.pth"

TEST:
  #checkpoint: "epoch_50.pth"
  result: "./test_dataset/"

DIR: "weights/outside30k-hrnetv2-ocr_test/"
