DATASET:
  root_dataset: "./data/"
  list_train: "./data/outside30k_train.odgt"
  list_val: "./data/outside30k_val.odgt"
  list_stats: "./data/outside30k_val.odgt"
  num_class: 27
  imgSizes: (300, 400, 500, 600, 700, 800)
  imgMaxSize: 1280
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True
  random_crop: False
  classInfo: "./data/outside30k.json"

MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "c1"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 30
  start_epoch: 0
  epoch_iters: 10000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "weights/outside30k-resnet50-c1"
